# Generated by Django 4.2.3 on 2024-07-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=None, editable=False, max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
