# Generated by Django 5.2.4 on 2025-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravitaillement',
            name='commanded_quantity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='product_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products_images/'),
        ),
    ]
