# Generated by Django 2.2.13 on 2024-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_etag',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
