# Generated by Django 5.1.7 on 2025-03-26 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_product_etag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_unity',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
