# Generated by Django 5.1.7 on 2025-03-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_unity_alter_shelf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.unity'),
        ),
    ]
