# Generated by Django 5.2.4 on 2025-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='sell_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
