# Generated by Django 5.2.4 on 2025-07-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_sell_sell_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
