# Generated by Django 5.2.4 on 2025-07-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_sell_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='cumuled_benefit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='total_benefit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
