# Generated by Django 5.2.4 on 2025-07-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_sell_cumuled_benefit_sell_total_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='cumuled_benefit',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='total_benefit',
        ),
        migrations.AlterField(
            model_name='sell',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
