# Generated by Django 5.2.4 on 2025-07-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_ravitaillement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravitaillement',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products_images/'),
        ),
    ]
