# Generated by Django 5.2.4 on 2025-07-25 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_ravitaillement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplieEntrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suppler_tel', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='products_images/')),
                ('date', models.DateTimeField(auto_now=True)),
                ('supplier_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
    ]
