# Generated by Django 5.2.4 on 2025-07-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_supplieentrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieentrance',
            name='supplier_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
