# Generated by Django 5.2.4 on 2025-07-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_supplieentrance_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieentrance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
