# Generated by Django 5.2.4 on 2025-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_supplieentrance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravitaillement',
            name='commanded_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
