# Generated by Django 5.2.4 on 2025-08-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_ravitaillement_commanded_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ravitaillement',
            name='commanded_quantity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
