# Generated by Django 5.2.3 on 2025-06-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='resolution',
            field=models.CharField(choices=[('1600x1200', 'UXGA'), ('1280x1024', 'SXGA'), ('1280x720', 'HD'), ('1024x768', 'XGA'), ('800x600', 'SVGA'), ('640x480', 'VGA'), ('480x320', 'HVGA'), ('400x296', 'CIF'), ('320x240', 'QVGA'), ('240x240', '240x240'), ('240x176', 'HQVGA'), ('176x144', 'QCIF'), ('128x128', '128x128'), ('160x120', 'QQVGA'), ('96x96', '96x96')], default='VGA', help_text='Select the camera resolution.', max_length=10),
        ),
    ]
