# Generated by Django 5.2.3 on 2025-06-17 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_alter_camera_hflip_alter_camera_vflip'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='contrast',
            field=models.IntegerField(default=0, help_text='Contrast level of the camera (-2-2).', validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='camera',
            name='brightness',
            field=models.IntegerField(default=0, help_text='Brightness level of the camera (-2-2).', validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='camera',
            name='quality',
            field=models.IntegerField(default=10, help_text='Quality of the camera stream (4-63).', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(63)]),
        ),
    ]
