# Generated by Django 5.2.3 on 2026-09-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_ravitaillement_commanded_quantity_sell_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.AlterField(
            model_name='sell',
            name='sell_date',
            field=models.DateTimeField(),
        ),
    ]
