# Generated by Django 5.2.3 on 2026-09-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='stock_deducted',
            field=models.IntegerField(default=0),
        ),
    ]
