# Generated by Django 5.2.3 on 2026-09-27 10:26

from django.db import migrations, models


def record_existing_prices(apps, schema_editor):
    """Existing sales and bill lines get the product's current prices: the
    prices they were really made at were never stored, so this is the best
    available value. From now on they are recorded at sale/bill time."""
    Sell = apps.get_model('store', 'Sell')
    BillItems = apps.get_model('store', 'BillItems')
    for sale in Sell.objects.filter(product__isnull=False).select_related('product'):
        sale.unit_cost = sale.product.product_cp
        sale.save(update_fields=['unit_cost'])
    for item in BillItems.objects.filter(product__isnull=False).select_related('product'):
        item.unit_price = item.product.product_sp
        item.save(update_fields=['unit_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_sell_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitems',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sell',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(record_existing_prices, migrations.RunPython.noop),
    ]
