# Generated by Django 5.2.3 on 2026-09-27 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_recorded_sale_and_bill_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('created', 'Création'), ('edited', 'Modification'), ('imported', 'Import CSV'), ('restocked', 'Ravitaillement')], max_length=20)),
                ('old_cost_price', models.FloatField(blank=True, null=True)),
                ('new_cost_price', models.FloatField()),
                ('old_selling_price', models.FloatField(blank=True, null=True)),
                ('new_selling_price', models.FloatField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='store.product')),
            ],
            options={
                'ordering': ['-changed_at', '-pk'],
            },
        ),
    ]
