# Generated by Django 5.2.3 on 2025-06-17 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_alter_camera_brightness_alter_camera_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='brightness',
            field=models.IntegerField(default=0, help_text='Brightness level of the camera (0-100).', validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='camera',
            name='quality',
            field=models.IntegerField(default=10, help_text='Quality of the camera stream (1-100).', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(63)]),
        ),
    ]
