# Generated by Django 5.2.3 on 2025-06-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_alter_camera_brightness_alter_camera_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='vflip',
            field=models.BooleanField(default=True, help_text='Vertical flip of the camera stream.'),
        ),
    ]
