# Generated by Django 5.2.3 on 2025-06-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_alter_camera_vflip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='hflip',
            field=models.BooleanField(default=True, help_text='Horizontal flip of the camera stream.'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='vflip',
            field=models.BooleanField(default=False, help_text='Vertical flip of the camera stream.'),
        ),
    ]
