# Generated by Django 5.2.3 on 2026-09-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_camera_contrast_alter_camera_brightness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Recordings older than this many days are deleted every night.')),
            ],
        ),
    ]
