# Generated by Django 5.2.3 on 2026-09-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_recording_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStreamSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion_camera_id', models.PositiveIntegerField(help_text="n of motionEye's camera-<n>.conf", unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
